name = "cloudn"
main = "src/index.js"
compatibility_date = "2026-01-01"
[vars]
PREVIEW_IMAGE_BASES = [
  "https://raw.githubusercontent.com/ourtaiko/chart-preview-database/refs/heads/main/charts",
]

[vars.FILE_MAP]
"/api/cnsongs" = [
  "https://raw.githubusercontent.com/OurTaiko/taiko-song-database-cn/refs/heads/main/songs.json",
  "https://gitea.com/OurTaiko/taiko-song-database-cn/raw/branch/main/songs.json",
]
"/api/fumendb_constants" = [
  "https://raw.githubusercontent.com/ourtaiko/fumen-database-scraper/refs/heads/main/songs.json",
]
"/api/previews" = [
  "https://raw.githubusercontent.com/ourtaiko/chart-preview-database/refs/heads/main/previews.json",
]
"/api/difficulty_chart/10/fc" = [
  "https://raw.githubusercontent.com/KirisameVanilla/difficulty-chart-database/refs/heads/main/10fc.json",
]
"/api/ese_mapping" = [
  "https://raw.githubusercontent.com/OurTaiko/ese-mapping-to-nijiiroid/refs/heads/main/data.json",
]
"/api/gugu_constants" = [
  "https://raw.githubusercontent.com/OurTaiko/Constants/refs/heads/main/constants.json",
  "https://gitea.com/OurTaiko/Constants/raw/branch/main/constants.json",
]
"/api/gugu_constants_test" = [
  "https://raw.githubusercontent.com/OurTaiko/Constants/refs/heads/dev/constants.json",
]
